import {
  faCalendarCheck,
  faUserDoctor,
  faUsers,
  faBell,
  faRightFromBracket,
  faShieldHalved,
  faGaugeHigh,
  faPlus,
  faXmark,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faMagnifyingGlass,
  faCircleExclamation,
  faClock,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faSpinner,
  faLock,
  faEnvelope,
  faPhone,
  faIdCard,
  faStethoscope,
  faHouseMedical,
  faTriangleExclamation,
  faShieldHeart,
  faCalendarDay,
  faClipboardList,
  faEye,
  faEyeSlash,
  faBars,
  faUserGear,
  faUserLock,
  faUserCheck,
  faCircleUser,
  faArrowUpRightFromSquare,
  faEnvelopeOpenText,
} from "@fortawesome/free-solid-svg-icons";
import { faGithub, faLinkedin, faXTwitter } from "@fortawesome/free-brands-svg-icons";

/**
 * Single source of truth for which icon represents which concept, so the same idea
 * (e.g. "appointment") always renders with the same glyph everywhere in the app.
 */
export const icons = {
  appointments: faCalendarCheck,
  doctors: faUserDoctor,
  patients: faUsers,
  notifications: faBell,
  logout: faRightFromBracket,
  mfa: faShieldHalved,
  dashboard: faGaugeHigh,
  add: faPlus,
  close: faXmark,
  confirm: faCheck,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  search: faMagnifyingGlass,
  error: faCircleExclamation,
  warning: faTriangleExclamation,
  clock: faClock,
  filter: faFilter,
  sort: faSort,
  sortUp: faSortUp,
  sortDown: faSortDown,
  spinner: faSpinner,
  password: faLock,
  email: faEnvelope,
  phone: faPhone,
  license: faIdCard,
  specialty: faStethoscope,
  brand: faHouseMedical,
  github: faGithub,
  linkedin: faLinkedin,
  twitter: faXTwitter,
  admin: faShieldHeart,
  auditLog: faClipboardList,
  manageUsers: faUserGear,
  lockUser: faUserLock,
  unlockUser: faUserCheck,
  account: faCircleUser,
  externalLink: faArrowUpRightFromSquare,
  reminder: faEnvelopeOpenText,
  dateOfBirth: faCalendarDay,
  menu: faBars,
  showPassword: faEye,
  hidePassword: faEyeSlash,
} as const;
